# agentic-worktree: module=host-elixir version=0.1.0
# Generated by sync-worktree-workflow. Edit the source in agentic-dotfiles,
# then re-run the sync script. Keep repo-specific overrides in Makefile
# before: include make/worktree.mk

# agentic-worktree-source: module=base version=0.1.0
#
# Shared worktree Make targets. This file is concatenated with one profile module
# into repo-local make/worktree.mk by sync-worktree-workflow.

RECURSIVE_MAKE ?= $(MAKE)
MAIN_BRANCH ?= main
WORKTREE_ROOT ?= ..
WORKTREE_CLEANUP_BASE ?= HEAD
WORKTREE_PRIMARY_PATH ?= $(shell git worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $$2; exit}')
WORKTREE_PROJECT ?= $(notdir $(WORKTREE_PRIMARY_PATH))
WORKTREE_NAME ?= $(notdir $(CURDIR))
WORKTREE_IS_PRIMARY ?= $(shell [ "$$(cd "$(CURDIR)" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ] && echo yes || echo no)
WORKTREE_CLEANUP_BASE_REV ?= $(shell git rev-parse "$(WORKTREE_CLEANUP_BASE)" 2>/dev/null || printf '%s' "$(WORKTREE_CLEANUP_BASE)")

.PHONY: worktree-new worktree-bootstrap smoke worktree-status worktree-info worktree-cleanup worktree-cleanup-all worktree-prune
.PHONY: wtn wtb wts wti wtc wtca

worktree-new: ## Create + bootstrap a new worktree from the current checkout. Usage: make worktree-new BRANCH=feature/x
	@if [ -z "$(BRANCH)" ]; then \
		echo "Usage: make worktree-new BRANCH=feature/my-feature"; \
		exit 1; \
	fi
	@SLUG=$$(printf '%s\n' "$(BRANCH)" | sed 's|.*/||; s|[^a-zA-Z0-9]|-|g; s|^-*||; s|-*$$||'); \
	if [ -z "$$SLUG" ]; then echo "Could not derive worktree slug from BRANCH=$(BRANCH)"; exit 1; fi; \
	DIR="$(WORKTREE_ROOT)/$(WORKTREE_PROJECT)-$$SLUG"; \
	if [ -e "$$DIR" ]; then echo "$$DIR already exists"; exit 1; fi; \
	echo "Creating worktree $$DIR for branch $(BRANCH) from current HEAD"; \
	git worktree add "$$DIR" -b "$(BRANCH)" HEAD && \
	$(RECURSIVE_MAKE) -C "$$DIR" worktree-bootstrap

worktree-bootstrap: ## Idempotent standup inside a linked worktree.
	@if [ "$(WORKTREE_IS_PRIMARY)" = "yes" ]; then \
		echo "worktree-bootstrap must run from a linked worktree, not the primary checkout"; \
		exit 1; \
	fi
	@$(RECURSIVE_MAKE) worktree-profile-bootstrap

smoke: ## Verify the worktree is ready for implementation.
	@$(RECURSIVE_MAKE) worktree-profile-smoke

worktree-status: ## Show all worktrees with branch and git status.
	@printf "\n  %-44s %-40s %s\n\n" "WORKTREE" "BRANCH" "GIT"
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git -C "$$wpath" rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		git_info=""; \
		if [ "$$dirty" != "0" ]; then git_info="$$dirty dirty"; fi; \
		if [ "$$unmerged" = "0" ]; then \
			if [ -n "$$git_info" ]; then git_info="merged, $$git_info"; else git_info="merged"; fi; \
		else \
			if [ -n "$$git_info" ]; then git_info="$$unmerged unmerged, $$git_info"; else git_info="$$unmerged unmerged"; fi; \
		fi; \
		printf "  %-44s %-40s %s\n" "$$name" "$$short_branch" "$$git_info"; \
	done; \
	echo ""

worktree-info: ## Display current worktree configuration.
	@echo "Project:          $(WORKTREE_PROJECT)"
	@echo "Worktree name:    $(WORKTREE_NAME)"
	@echo "Path:             $(CURDIR)"
	@echo "Primary checkout: $(WORKTREE_PRIMARY_PATH)"
	@echo "Is primary:       $(WORKTREE_IS_PRIMARY)"
	@echo "Cleanup base:     $(WORKTREE_CLEANUP_BASE) ($(WORKTREE_CLEANUP_BASE_REV))"
	@$(RECURSIVE_MAKE) worktree-profile-info

worktree-cleanup: ## Remove one clean, merged worktree. Usage: make worktree-cleanup NAME=<worktree-name>
	@if [ -z "$(NAME)" ]; then \
		echo "Usage: make worktree-cleanup NAME=<worktree-name>"; \
		exit 1; \
	fi
	@DIR="$(WORKTREE_ROOT)/$(NAME)"; \
	if [ ! -d "$$DIR" ]; then echo "$$DIR does not exist"; exit 1; fi; \
	if [ "$$(cd "$$DIR" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then \
		echo "Refusing to remove primary checkout $$DIR"; exit 1; \
	fi; \
	if [ -n "$$(git -C "$$DIR" status --porcelain 2>/dev/null)" ]; then \
		echo "$$DIR is dirty; commit or stash first"; exit 1; \
	fi; \
	BRANCH=$$(git -C "$$DIR" rev-parse --abbrev-ref HEAD); \
	UNMERGED=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$BRANCH" --count 2>/dev/null || echo "?"); \
	if [ "$$UNMERGED" != "0" ]; then \
		echo "$$BRANCH has $$UNMERGED commits not merged into $(WORKTREE_CLEANUP_BASE); refusing"; exit 1; \
	fi; \
	$(RECURSIVE_MAKE) worktree-profile-before-cleanup NAME="$(NAME)"; \
	echo "Removing worktree $$DIR (branch $$BRANCH)"; \
	git worktree remove "$$DIR" && git branch -d "$$BRANCH"

worktree-cleanup-all: ## Remove every clean worktree merged into WORKTREE_CLEANUP_BASE.
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		if [ "$$(cd "$$wpath" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then continue; fi; \
		if [ "$$short_branch" = "$$(git rev-parse --abbrev-ref HEAD)" ]; then continue; fi; \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		if [ "$$dirty" = "0" ] && [ "$$unmerged" = "0" ]; then \
			$(RECURSIVE_MAKE) worktree-cleanup NAME="$$name"; \
		fi; \
	done

worktree-prune: ## Prune git metadata for missing worktree directories.
	@git worktree prune -v

wtn: worktree-new ## Alias for worktree-new
wtb: worktree-bootstrap ## Alias for worktree-bootstrap
wts: worktree-status ## Alias for worktree-status
wti: worktree-info ## Alias for worktree-info
wtc: worktree-cleanup ## Alias for worktree-cleanup
wtca: worktree-cleanup-all ## Alias for worktree-cleanup-all

# agentic-worktree-source: module=host-elixir version=0.1.0

.PHONY: worktree-profile-bootstrap worktree-profile-smoke worktree-profile-info worktree-profile-before-cleanup

worktree-profile-bootstrap:
	@if [ -f mix.exs ]; then \
		mix deps.get; \
		$(RECURSIVE_MAKE) smoke; \
	else \
		echo "No mix.exs found; skipping Elixir bootstrap"; \
	fi

worktree-profile-smoke:
	@if [ ! -f mix.exs ]; then echo "mix.exs not found"; exit 1; fi
	@mix compile --warnings-as-errors
	@mix test --max-failures 1

worktree-profile-info:
	@echo "Profile:          host-elixir"

worktree-profile-before-cleanup:
	@:
