# agentic-worktree: module=host-elixir version=0.2.8
# Generated by sync-worktree-workflow. Edit the source in agentic-dotfiles,
# then re-run the sync script. Keep repo-specific overrides in Makefile
# before: include make/worktree.mk

# agentic-worktree-source: module=host-elixir version=0.2.1

.PHONY: worktree-profile-bootstrap worktree-profile-smoke worktree-profile-info worktree-profile-before-cleanup

worktree-profile-bootstrap:
	@if [ -f mix.exs ]; then \
		mix deps.get; \
		$(RECURSIVE_MAKE) smoke; \
	else \
		echo "No mix.exs found; skipping Elixir bootstrap"; \
	fi

worktree-profile-smoke:
	@if [ ! -f mix.exs ]; then echo "mix.exs not found"; exit 1; fi
	@mix compile --warnings-as-errors
	@mix test --max-failures 1

worktree-profile-info:
	@printf "%bProfile:%b          host-elixir\n" "$(WT_BOLD)" "$(WT_RESET)"

worktree-profile-before-cleanup:
	@:

# agentic-worktree-source: module=base version=0.2.6
#
# Shared worktree Make targets. This file is concatenated with one profile module
# into repo-local make/worktree.mk by sync-worktree-workflow.

# 1Password account used by any target that calls `op` (e.g. `make env` that
# does `op inject -i .env.tpl -o .env`). The `op` CLI honors the OP_ACCOUNT
# env var, so exporting it makes every bare `op` invocation in any target
# inherit this account — no need to refactor targets to use $(OP). $(OP) is
# also provided for explicit/portable use. Override per-repo if your secrets
# live in a different account.
OP_ACCOUNT ?= team-chapterspot
OP ?= op --account $(OP_ACCOUNT)
export OP_ACCOUNT

RECURSIVE_MAKE ?= $(MAKE)
MAIN_BRANCH ?= main
WORKTREE_ROOT ?= ..
WORKTREE_CLEANUP_BASE ?= HEAD
WORKTREE_PRIMARY_PATH ?= $(shell git worktree list --porcelain 2>/dev/null | awk '/^worktree /{print $$2; exit}')
WORKTREE_PROJECT ?= $(notdir $(WORKTREE_PRIMARY_PATH))
WORKTREE_NAME ?= $(notdir $(CURDIR))
WORKTREE_IS_PRIMARY ?= $(shell [ "$$(cd "$(CURDIR)" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ] && echo yes || echo no)
WORKTREE_CLEANUP_BASE_REV ?= $(shell git rev-parse "$(WORKTREE_CLEANUP_BASE)" 2>/dev/null || printf '%s' "$(WORKTREE_CLEANUP_BASE)")
WORKTREE_COLOR ?= auto
# Colors enabled unless explicitly disabled. We can't detect TTY from inside
# $(shell ...) (it's always a pipe), and MAKE_TERMOUT only appears when Make's
# stdout is a terminal — so default to on and let NO_COLOR / "never" opt out.
WORKTREE_COLOR_ENABLED ?= $(shell if [ "$(WORKTREE_COLOR)" = "never" ] || [ -n "$(NO_COLOR)" ] || [ -n "$$NO_COLOR" ]; then echo no; else echo yes; fi)

ifeq ($(WORKTREE_COLOR_ENABLED),yes)
WT_BOLD := \033[1m
WT_DIM := \033[90m
WT_GREEN := \033[32m
WT_YELLOW := \033[33m
WT_RED := \033[31m
WT_CYAN := \033[36m
WT_RESET := \033[0m
else
WT_BOLD :=
WT_DIM :=
WT_GREEN :=
WT_YELLOW :=
WT_RED :=
WT_CYAN :=
WT_RESET :=
endif

.PHONY: worktree-new worktree-bootstrap smoke worktree-status worktree-info worktree-cleanup worktree-cleanup-all worktree-prune
.PHONY: wtn wtb wts wti wtc wtca

worktree-new: ## Create + bootstrap a new worktree from the current checkout. Usage: make worktree-new BRANCH=feature/x
	@if [ -z "$(BRANCH)" ]; then \
		echo "Usage: make worktree-new BRANCH=feature/my-feature"; \
		exit 1; \
	fi
	@SLUG=$$(printf '%s\n' "$(BRANCH)" | sed 's|.*/||; s|[^a-zA-Z0-9]|-|g; s|^-*||; s|-*$$||'); \
	if [ -z "$$SLUG" ]; then echo "Could not derive worktree slug from BRANCH=$(BRANCH)"; exit 1; fi; \
	DIR="$(WORKTREE_ROOT)/$(WORKTREE_PROJECT)-$$SLUG"; \
	if [ -e "$$DIR" ]; then echo "$$DIR already exists"; exit 1; fi; \
	printf "%b\n" "$(WT_BOLD)Creating worktree$(WT_RESET) $$DIR for branch $(WT_CYAN)$(BRANCH)$(WT_RESET) from current HEAD"; \
	git worktree add "$$DIR" -b "$(BRANCH)" HEAD && \
	$(RECURSIVE_MAKE) -C "$$DIR" worktree-bootstrap

worktree-bootstrap: ## Idempotent standup inside a linked worktree.
	@if [ "$(WORKTREE_IS_PRIMARY)" = "yes" ]; then \
		echo "worktree-bootstrap must run from a linked worktree, not the primary checkout"; \
		exit 1; \
	fi
	@$(RECURSIVE_MAKE) worktree-profile-bootstrap

smoke: ## Verify the worktree is ready for implementation.
	@$(RECURSIVE_MAKE) worktree-profile-smoke

ifndef WORKTREE_PROFILE_PROVIDES_STATUS
worktree-status: ## Show all worktrees with branch and git status.
	@printf "\n  %b%-44s %-40s %s%b\n\n" "$(WT_BOLD)" "WORKTREE" "BRANCH" "GIT" "$(WT_RESET)"
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git -C "$$wpath" rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		git_info=""; \
		if [ "$$dirty" != "0" ]; then git_info="$(WT_YELLOW)$$dirty dirty$(WT_RESET)"; fi; \
		if [ "$$unmerged" = "0" ]; then \
			if [ -n "$$git_info" ]; then git_info="$(WT_GREEN)merged$(WT_RESET), $$git_info"; else git_info="$(WT_GREEN)merged$(WT_RESET)"; fi; \
		else \
			if [ -n "$$git_info" ]; then git_info="$(WT_CYAN)$$unmerged unmerged$(WT_RESET), $$git_info"; else git_info="$(WT_CYAN)$$unmerged unmerged$(WT_RESET)"; fi; \
		fi; \
		printf "  %-44s %-40s %b\n" "$$name" "$$short_branch" "$$git_info"; \
	done; \
	echo ""
endif

worktree-info: ## Display current worktree configuration.
	@printf "%bProject:%b          %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_PROJECT)"
	@printf "%bWorktree name:%b    %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_NAME)"
	@printf "%bPath:%b             %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(CURDIR)"
	@printf "%bPrimary checkout:%b %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_PRIMARY_PATH)"
	@printf "%bIs primary:%b       %s\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_IS_PRIMARY)"
	@printf "%bCleanup base:%b     %s (%s)\n" "$(WT_BOLD)" "$(WT_RESET)" "$(WORKTREE_CLEANUP_BASE)" "$(WORKTREE_CLEANUP_BASE_REV)"
	@$(RECURSIVE_MAKE) worktree-profile-info

worktree-cleanup: ## Remove one clean, merged worktree. Usage: make worktree-cleanup NAME=<worktree-name>
	@if [ -z "$(NAME)" ]; then \
		echo "Usage: make worktree-cleanup NAME=<worktree-name>"; \
		exit 1; \
	fi
	@DIR="$(WORKTREE_ROOT)/$(NAME)"; \
	if [ ! -d "$$DIR" ]; then echo "$$DIR does not exist"; exit 1; fi; \
	if [ "$$(cd "$$DIR" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then \
		echo "Refusing to remove primary checkout $$DIR"; exit 1; \
	fi; \
	if [ -n "$$(git -C "$$DIR" status --porcelain 2>/dev/null)" ]; then \
		echo "$$DIR is dirty; commit or stash first"; exit 1; \
	fi; \
	BRANCH=$$(git -C "$$DIR" rev-parse --abbrev-ref HEAD); \
	UNMERGED=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$BRANCH" --count 2>/dev/null || echo "?"); \
	if [ "$$UNMERGED" != "0" ]; then \
		echo "$$BRANCH has $$UNMERGED commits not merged into $(WORKTREE_CLEANUP_BASE); refusing"; exit 1; \
	fi; \
	$(RECURSIVE_MAKE) worktree-profile-before-cleanup NAME="$(NAME)"; \
	printf "%b\n" "Removing worktree $(WT_CYAN)$$DIR$(WT_RESET) (branch $(WT_CYAN)$$BRANCH$(WT_RESET))"; \
	git worktree remove "$$DIR" && git branch -d "$$BRANCH"

worktree-cleanup-all: ## Remove every clean worktree merged into WORKTREE_CLEANUP_BASE.
	@git worktree list --porcelain | awk '/^worktree /{path=$$2} /^branch /{branch=$$2; print path "\t" branch}' | \
	while IFS=$$'\t' read -r wpath branch; do \
		name=$$(basename "$$wpath"); \
		short_branch=$$(printf '%s\n' "$$branch" | sed 's|refs/heads/||'); \
		if [ "$$(cd "$$wpath" 2>/dev/null && pwd -P)" = "$$(cd "$(WORKTREE_PRIMARY_PATH)" 2>/dev/null && pwd -P)" ]; then continue; fi; \
		if [ "$$short_branch" = "$$(git rev-parse --abbrev-ref HEAD)" ]; then continue; fi; \
		dirty=$$(git -C "$$wpath" status --porcelain 2>/dev/null | wc -l | tr -d ' '); \
		unmerged=$$(git rev-list "$(WORKTREE_CLEANUP_BASE_REV)".."$$short_branch" --count 2>/dev/null || echo "?"); \
		if [ "$$dirty" = "0" ] && [ "$$unmerged" = "0" ]; then \
			$(RECURSIVE_MAKE) worktree-cleanup NAME="$$name"; \
		fi; \
	done

worktree-prune: ## Prune git metadata for missing worktree directories.
	@git worktree prune -v

wtn: worktree-new ## Alias for worktree-new
wtb: worktree-bootstrap ## Alias for worktree-bootstrap
wts: worktree-status ## Alias for worktree-status
wti: worktree-info ## Alias for worktree-info
wtc: worktree-cleanup ## Alias for worktree-cleanup
wtca: worktree-cleanup-all ## Alias for worktree-cleanup-all
